language: c
dist: bionic

compiler:
 - gcc
 - clang

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq cmake
- pip install --user cpp-coveralls

install: true

script:
- cmake -DALPHA0_CHECK_COVERAGE=TRUE ./
- cmake --build ./
- ctest -VV -S

after_success:
- coveralls --gcov-options '\-lp'
