language: c
dist: trusty

compiler:
 - gcc
 - clang

env:
  global:
    - CTEST_EXT_COLOR_OUTPUT=TRUE
    - CTEST_BUILD_FLAGS=-j4

matrix:
  include:
    - os: linux
      compiler: gcc
      env: CTEST_TARGET_SYSTEM=Linux-gcc CTEST_MODEL=Nightly
    - os: linux
      compiler: clang
      env: CTEST_TARGET_SYSTEN=Linux-clang CTEST_MODEL=Nightly

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq cmake

install: true

script:
- mkdir build
- cd build
- cmake ../
- cmake --build ./
- ctest -VV -S
