language: c
dist: trusty

compiler:
 - gcc
 - clang

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq cmake
- pip install --user cpp-coveralls

install: true

script:
- mkdir build
- cd build
- cmake ../
- cmake --build ./
- ctest -VV -S

after_success:
- coveralls --gcov-options '\-lp'
